Add PR template and travis checks
Otus-DevOps-2020-11/ASobakin_infra pull request #1
Opened 2020-12-24 12:51 UTC by ASobakin

Add PR template and travis checks

2020-12-25 05:50 UTC, mrgreyves requested changes
Здравствуйте!) Домашние задания стоит выполнять в репозиториях которые были созданы для вас. Нужно переделать, дз возвращаю на доработку.

2020-12-25 06:52 UTC, ASobakin commented
А для кого был создан Asobakin_infra если не для меня?)

С уважением,
Собакин Александр Дмитриевич
Ведущий инженер-эксперт
Команда "FA#-Фондовый рынок. Финансовый Результат на Фондовых рынках"
Продуктовое направление "Фондовые рынки"
ПЦ "Финансовые рынки" FA#
Компания «Диасофт»
Всё по-настоящему!

Россия, 150001, г. Ярославль, Московский проспект, д.53
тел. (4852) 66-00-73, 66-00-74, 66-00-75
e-mail: asobakin@diasoft.ru<mailto:asobakin@diasoft.ru>
http://www.diasoft.ru<http://www.diasoft.ru/>

From: Vladimir Drozdetskiy [mailto:notifications@github.com]
Sent: Friday, December 25, 2020 8:51 AM
To: Otus-DevOps-2020-11/ASobakin_infra
Cc: Собакин Александр; Author
Subject: Re: [Otus-DevOps-2020-11/ASobakin_infra] Add PR template and travis checks (#1)


@mrgreyves requested changes on this pull request.

Здравствуйте!) Домашние задания стоит выполнять в репозиториях которые были созданы для вас. Нужно переделать, дз возвращаю на доработку.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Otus-DevOps-2020-11/ASobakin_infra/pull/1#pullrequestreview-558761131>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASBWUQSDJHA6AY3KRFLYJB3SWQR3ZANCNFSM4VIFORWA>.

2020-12-30 07:49 UTC, mrgreyves requested changes
![image](https://user-images.githubusercontent.com/34331259/103337483-9b851880-4a8c-11eb-8b7a-db91f5460f14.png)
1 - откуда делается пр
2 - куда делается ПР
То есть вы не должны были форкать себе ВАШ репозиторий, а уже сразу работать в нем. Понятно что имею ввиду?)

2020-12-30 08:01 UTC, ASobakin commented
Ага. Теперь понятно)

С уважением,
Собакин Александр Дмитриевич
Ведущий инженер-эксперт
Команда "FA#-Фондовый рынок. Финансовый Результат на Фондовых рынках"
Продуктовое направление "Фондовые рынки"
ПЦ "Финансовые рынки" FA#
Компания «Диасофт»
Всё по-настоящему!

Россия, 150001, г. Ярославль, Московский проспект, д.53
тел. (4852) 66-00-73, 66-00-74, 66-00-75
e-mail: asobakin@diasoft.ru<mailto:asobakin@diasoft.ru>
http://www.diasoft.ru<http://www.diasoft.ru/>

From: Vladimir Drozdetskiy [mailto:notifications@github.com]
Sent: Wednesday, December 30, 2020 10:50 AM
To: Otus-DevOps-2020-11/ASobakin_infra
Cc: Собакин Александр; Author
Subject: Re: [Otus-DevOps-2020-11/ASobakin_infra] Add PR template and travis checks (#1)


@mrgreyves requested changes on this pull request.

[image]<https://user-images.githubusercontent.com/34331259/103337483-9b851880-4a8c-11eb-8b7a-db91f5460f14.png>
1 - откуда делается пр
2 - куда делается ПР
То есть вы не должны были форкать себе ВАШ репозиторий, а уже сразу работать в нем. Понятно что имею ввиду?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Otus-DevOps-2020-11/ASobakin_infra/pull/1#pullrequestreview-559941492>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASBWUQVJTRKB4FJPE7NSW7TSXLLSTANCNFSM4VIFORWA>.

2021-01-01 13:37 UTC, closed without merging